name: Sync with Upstream

on:
  schedule:
    - cron:  '0 7 * * 1,4'
    # scheduled at 07:00 every Monday and Thursday
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
    - name: Checkout origin
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v1
      with:
        upstream_repository: mordentral/AdvancedSessionsPlugin
        upstream_branch: master
        target_branch: origin
        github_token: ${{ secrets.REPO_SCOPED_TOKEN }}

    - if: steps.sync.outputs.has_new_commits
      name: Turn master into the AdvancedSessions plugin.
      run: |
        if [[ "$ref_synced" != "$ref_current" ]]; then
          git subtree split -P ./AdvancedSessions -b master origin
          git push origin master --force
        fi

    - if: steps.sync.outputs.has_new_commits
      name: Add workflows into master because Github is janky
      run: |
        git fetch --all
        git checkout master
        git restore --source workflows .github
        git commit -am "add .github workflows"
        git push origin master
