on:
  schedule:
    - cron:  '0 7 * * 1,4'
    # scheduled at 07:00 every Monday and Thursday

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
    - name: Checkout origin
      uses: actions/checkout@v2
      with:
        ref: origin
        
    - name: Get HEAD 
      run: echo "ref_current=$GITHUB_REF" >> $GITHUB_ENV

    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v1
      with:
        upstream_repository: mordentral/AdvancedSessionsPlugin
        upstream_branch: master

    - name: Get new HEAD 
      run: echo "ref_synced=$GITHUB_REF" >> $GITHUB_ENV
    
    - name: Timestamp
      run: date  
    
    - name: Run 
      run: |
        if [[ "$ref_synced" != "$ref_current" ]]; then #it's updated
          git subtree split -P ./AdvancedSessions -b master origin
          git push origin master --force
        fi 


    
